esphome:
  name: bistro-lights
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret bistro_ota
ota:
  password: !secret bistro_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bistro-Lights Fallback Hotspot"
    password: "iY8MFEMulkl8"

captive_portal:

web_server:
  port: 80

uart:
   rx_pin: GPIO3
   tx_pin: GPIO1
   baud_rate: 9600

time:
  - platform: homeassistant
    id: esptime

# [00:51:53][C][tuya:028]: Tuya:
# [00:51:53][C][tuya:039]:   Datapoint 1: switch (value: OFF)
# [00:51:53][C][tuya:041]:   Datapoint 2: int value (value: 653)
# [00:51:53][C][tuya:041]:   Datapoint 3: int value (value: 183)
# [00:51:53][C][tuya:045]:   Datapoint 4: enum (value: 0)
# [00:51:53][C][tuya:041]:   Datapoint 102: int value (value: 0)
# [00:51:53][C][tuya:055]:   Product: '{"p":"w5aawsfeplzszdhx","v":"2.2.8","m":0}'

# Register the Tuya MCU connection
tuya:
  time_id: esptime

light:
  - platform: "tuya"
    name: "Bistro Lights"
    dimmer_datapoint: 2
    min_value_datapoint: 3
    switch_datapoint: 1
    max_value: 1000
    min_value: 10
    restore_mode: ALWAYS_OFF
    