# Disable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption

ota:
  password: !secret esphome_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret esphome_fallback

captive_portal:

time:
  - platform: homeassistant
    id: esptime

button:
  - platform: safe_mode
    name: "${friendly_name} Restart in Safe Mode"
    internal: true

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    internal: true
  - platform: template
    id: esphome_device_update_available
    device_class: update
    name: "${friendly_name} Update available"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    internal: true