esphome:
  name: desk-lamp
  platform: 'ESP8266'
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret desk_lamp_ota

ota:
  password: !secret desk_lamp_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desk-Lamp Fallback Hotspot"
    password: "ZWkYC0p8ff20"

captive_portal:

web_server:
  port: 80

light:
  - platform: binary
    name: "Desk Lamp"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: D1