esphome:
  name: kitchen-counter
  platform: ESP8266
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret kitchen_counter_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Counter Fallback Hotspot"
    password: "nOAEJpl9mKGD"

captive_portal:

light:
  - platform: rgbww
    name: "Kitchen Counter Light"
    id: "counter_light"
    red: output_component1
    green: output_component2
    blue: output_component3
    cold_white: output_component4
    warm_white: output_component5
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 1700 K
    color_interlock: true

# Example output entry
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_component2
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_component3
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_component4
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_component5
    pin: GPIO13


binary_sensor:
  - platform: gpio
    pin: GPIO0
    id: "button"
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - logger.log: "button pushed"
        - light.toggle: 
            id: counter_light
            transition_length: 500ms
        - logger.log: "light toggled"