substitutions:
  name: m5stack-atom-echo-8046b4
  friendly_name: Bedroom Speaker
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: /UPn0D62kzcHTPRtOm9qoVGJ5FkL5+n3FEzM/kfKquk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
