substitutions:
  name: m5stack-atom-echo-80b9f0
  friendly_name: office-speaker
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: POsg29dYL5oU9F0Hccf1KD5rswozccf42htOWKkAcbo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
