substitutions:
  name: m5stack-atom-echo-8046b4
  friendly_name: bedroom-speaker
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: mQhuJ1chMjzYgoJtLvIhjDtOnei9Z6HmVj5BaKoSkrk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
