esphome:
  name: monster-strip
  friendly_name: Monster Lamp

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "spR+XUh8lKZiFxBTDhxQXR5Y976VNL2P+OxOJz+0zy4="

ota:
  password: "3b5d9448f9804283b3124338dd7ac0f4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Monster-Strip Fallback Hotspot"
    password: "kZ679sWz4Mf3"

captive_portal:
    