substitutions:
  friendly_name: Outside Plug
esphome:
  name: outside-plug
  platform: ESP8266
  board: esp8285

packages:
  common: !include base/common.template.yaml

switch:
  - platform: gpio
    pin: 13
    name: "Outside Plug"
    id: relay

binary_sensor:
  - platform: gpio
    pin: 4
    id: power_button
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay