esphome:
  name: plants
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
     # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Yap House"
  password: "squeakthec0y0te"
  #fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "plants Fallback Hotspot"
    password: "1Xzqff400HYc"

# web_server:
#   port: 80

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: my_green
    red: 0%
    green: 100%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: my_gray
    red: 50%
    green: 50%
    blue: 50%

font:
  - file: "LiberationSans.ttf"
    id: liberationsans_48
    size: 48
  - file: "LiberationSans.ttf"
    id: liberationsans_24
    size: 24
  - file: "LiberationSans.ttf"
    id: liberationsans_12
    size: 12

binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    name: "T-Display Button Input 0"
    id: tdisplay_button_input_0
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "T-Display Button Input 1"
    id: tdisplay_button_input_1

switch:
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight

time:
  - platform: homeassistant
    id: esptime

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

esp32_ble_tracker:

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6C:A2:8D'
    temperature:
      name: "Coleus Temperature"
      id: ble_temp
    moisture:
      name: "Coleus Moisture"
      id: ble_moist
    illuminance:
      name: "Coleus Illuminance"
      id: ble_light
    conductivity:
      name: "Coleus Soil Conductivity"
      id: ble_soilv

interval:
  - interval: 15s
    then:
      - display.page.show_next: my_display
      - component.update: my_display

image:
  - file: "img/water-percent.png"
    id: 'water_percent'
    type: GRAYSCALE

# display is 240x135
display:
  - platform: st7789v
    id: my_display
    backlight_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO16
    reset_pin: GPIO23
    rotation: 270
    pages:
      - id: time_page
        lambda: |-
          it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_blue));
          it.rectangle(0, 20, it.get_width(), it.get_height(), id(my_blue));   // header bar

          it.strftime((240 / 2), (140 / 3) * 1 + 5, id(liberationsans_24), id(my_gray), TextAlign::CENTER, "%Y-%m-%d", id(esptime).now());
          it.strftime((240 / 2), (140 / 3) * 2 + 5, id(liberationsans_48), id(my_gray), TextAlign::CENTER, "%H:%M", id(esptime).now());
          it.print(5, 5, id(liberationsans_12), id(my_yellow), TextAlign::TOP_LEFT, "ESPHome");

          // Comment out the above lines to see the image without text overlaid
          // it.image(0, 0, id(my_image));

          if (id(system_status).state) {
            it.print(235, 5, id(liberationsans_12), id(my_green), TextAlign::TOP_RIGHT, "Online");
          }
          else {
            it.print(235, 5, id(liberationsans_12), id(my_red), TextAlign::TOP_RIGHT, "Offline");
          }
      - id: moisture_page
        lambda: |-
          it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_blue));
          it.rectangle(0, 20, it.get_width(), it.get_height(), id(my_blue));   // header bar

          it.strftime(235,5, id(liberationsans_12), id(my_gray), TextAlign::TOP_RIGHT, "%Y-%m-%d", id(esptime).now());
          it.strftime(5, 5, id(liberationsans_12), id(my_gray), TextAlign::TOP_LEFT, "%H:%M:%S", id(esptime).now());
          // it.strftime((240 / 2), (140 / 3) * 1 + 5, id(liberationsans_24), id(my_gray), TextAlign::CENTER, "%Y-%m-%d", id(esptime).now());
          // it.strftime((240 / 2), (140 / 3) * 2 + 5, id(liberationsans_48), id(my_gray), TextAlign::CENTER, "%H:%M:%S", id(esptime).now());

          // Comment out the above lines to see the image without text overlaid
          it.image(10, 30, id(water_percent));
          it.print(85, 30, id(liberationsans_24), id(my_gray), TextAlign::TOP_LEFT, "Coleus");
          it.printf(85, (140 / 3) * 1 + 30, id(liberationsans_48),id(my_gray), TextAlign::TOP_LEFT, "%.0f %%", id(ble_moist).state );