esphome:
  name: prism-light

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Prism-Light Fallback Hotspot"
    password: "lLTlK5z1u4Lo"

captive_portal:

uart:
   rx_pin: GPIO3
   tx_pin: GPIO1
   baud_rate: 9600

time:
  - platform: homeassistant
    id: esptime
tuya:
  time_id: esptime
  # on_datapoint_update:
  #   - sensor_datapoint: 24
  #     datapoint_type: any
  #     then:
  #       - lambda: |-
  #           return;

# power: 20
# brightness: 22
#   range: 10-1000
# color_temp: 23
#   range: 2700-6500
# color_mode: 21
# color: 24
# scene: 101
#   id: any byte
#   sp: speed, 0x64
#   mo: mode, 0x[fade,flash,music]
#   pt: pattern, 0x[solid,up,down,center,stripe,out,in,rot,spiral]
#   HSV: 0x0168, 0x03e8, (0x000a:0x03e8)
#   effect_bytes: {id}{sp}{mo}{pt}[colors:{hue}{sat}{vals}0000]
light:
  - platform: tuya
    name: Prism
    id: prism
    icon: 'mdi:triangle-outline'
    switch_datapoint: 20
    dimmer_datapoint: 22
    hsv_datapoint: 24
    color_temperature_datapoint: 23
    color_temperature_max_value: 255
    min_value: 10
    max_value: 1000
    cold_white_color_temperature: 6500K
    warm_white_color_temperature: 2700K
    effects:
      - lambda:
          name: Hyperion
          update_interval: 1s
          lambda: |-
            ESP_LOGD("Button","Enter function");
            const std::string pattern = "0b10320003001c03e803e800000000012c03c003e80000000000c703e803e800000000";
            uint8_t dp = 101;
            ESP_LOGD("Button","Attempting to write");
            tuya::Tuya tmcu;
            tmcu.set_string_datapoint_value(dp, pattern);
# tuya::Tuya tuyamcu;
# tuyamcu.set_string_datapoint_value(dp, pattern);
# ESP_LOGD("Button","Wrote!");
