esphome:
  name: seedlings
  platform: ESP32
  board: featheresp32

wifi:
  ssid: "Yap House"
  password: "squeakthec0y0te"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Seedlings Fallback Hotspot"
    password: "0LBizVlkEyda"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A2
    name: "Soil Sensor"
    id: soil
    update_interval: 10s
    attenuation: 11db
  - platform: dht
    pin: GPIO21
    temperature:
      name: "Seedling Box Temperature"
      id: temp
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Seedling Box Humidity"
      id: hum
    update_interval: 10s

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO18

display:
  - platform: waveshare_epaper
    cs_pin: GPIO26
    dc_pin: GPIO25
    busy_pin: GPIO16
    reset_pin: GPIO17
    model: 2.90in-b
    update_interval: 300s
    rotation: 270
    lambda: |-
      it.printf(0,0, id(mono), "Temp: %.1f°F", id(temp).state);
      it.printf(0,41, id(mono), "Hum:  %.1f%%", id(hum).state);
      it.printf(0,82, id(mono), "Soil: %.1f", id(soil).state);

font:
  - id: mono
    file: "Inconsolata-Regular.ttf"
    size: 30

