esphome:
  name: socket-1
  friendly_name: socket-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "9Xn55JjRX6XPIkvVLG8T3tuG0BgHbsS9oyqIjZIzZ5M="

ota:
  password: "2f1f5d5f2c5120fb03a4834d589a55a2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Socket-1 Fallback Hotspot"
    password: "uril1b7WYtHq"

captive_portal:
    