substitutions:
  friendly_name: Teckin BR30 f1ed64
  icon: "mdi:lightbulb-spot"

esphome:
  name: teckin-br30-f1ed64
  #name_add_mac_suffix: true
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret walf_ssid 
      password: !secret walf_password
    - ssid: !secret wifi_ssid 
      password: !secret wifi_password
  ap:
    password: !secret walf_secret

captive_portal:
logger:
api:

ota:

web_server:
  port: 80
  version: 1

output:
 - platform: esp8266_pwm
   id: output_red
   pin: GPIO4
 - platform: esp8266_pwm
   id: output_green
   pin: GPIO12
 - platform: esp8266_pwm
   id: output_blue
   pin: GPIO14
 - platform: esp8266_pwm
   id: output_warm_white
   pin: GPIO13
 - platform: esp8266_pwm
   id: output_cold_white
   pin: GPIO5

# Define a light entity
light:
  - platform: rgbww
    name: ${friendly_name} Light
    id: teckin_13w_rgbww
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 2800 K
    color_interlock: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
        - light.turn_on:
            id: teckin_13w_rgbww
            brightness: !lambda 'return id(brightness).state / 100.0;'
            color_temperature: !lambda 'return 1000000.0 / float(id(color_temp).state);'

number:
  - platform: template
    name: "${friendly_name} Color Temperature"
    id: color_temp
    optimistic: true
    min_value: 2800
    max_value: 6200
    initial_value: 3500
    restore_value: true
    step: 50
    on_value:
      then:  
        - if:
            condition:
              light.is_on: teckin_13w_rgbww
            then:
              - light.turn_on:
                  id: teckin_13w_rgbww
                  color_temperature: !lambda 'return 1000000.0 / float(x);'
  - platform: template
    name: "${friendly_name} Brightness"
    id: brightness
    optimistic: true
    min_value: 1
    max_value: 100
    initial_value: 100
    restore_value: true
    step: 1
    on_value:
      then:  
        - if:
            condition:
              light.is_on: teckin_13w_rgbww
            then:
              - light.turn_on:
                  id: teckin_13w_rgbww
                  brightness: !lambda 'return x / 100.0;'