substitutions:
  friendly_name: Weather Radio Alert
esphome:
  name: weather-radio
  platform: ESP8266
  board: d1_mini

packages:
  common: !include base/common.template.yaml

binary_sensor:
  - platform: gpio
    friendly_name: "Weather Radio External Alarm"
    name: "SAME Alarm"
    id: alarm
    device_class: safety
    pin:
      number: D2
      mode:
        input: true
        pullup: true
      inverted: true
      